### ISSUE TITLE
rebuild system with new architecture

### ISSUE THREAD

**Issue by fsImageries** [fsImageries/rev_space_timeline#102]
### TODOS
- [x] build planets
    - [x] need atmo component
    - [x] need orb component
    - [ ] ~need texture component~
    - [ ] ~need planet uniforms updater~
    - [x] need orb system
- [x] build parent system 
- [x] build raycaster system
- [x] implement 2d-rendered sprites
- [x] uniforms sun system
- [x] implement jumping to focus target
- [x] fix tests (window needs to be mocked to refactored out)
