### ISSUE TITLE
implement ecs

### ISSUE THREAD

**Issue by fsImageries** [fsImageries/rev_space_timeline#99]
# Task:
- [x] add entities
- [x] add components
- [x] add system
- [x] add system manager
- [x] add entity manager
- [x] add component manager
- [x] implement world
- [x] implement basic sphere to visualize
- [x] implement basic app to satisfy the compiler
- [x] add init step to load setup components which need extra steps
- [x] implement level manager (group manager basically)
- [x] implement query operands
- [x] implement component dependencies on same entity (parent-/rotgroup)
- [x] implement loop
    - add resize function
- [x] implement sun (with components)
- [ ] implement planet (with components)
- [x] implement multiple entities
- [ ] implement levelmanager excludes (eg. renderer)
- [x] implement uniform component (eg. sun)
- [x] implement type query for systems
- [x] implement data component
- [x] build alpha cosmic map
- [x] build disklines (maybe with convenience function)
- [x] build object lines
- [x] build ring entity
- [x] build text component

### Quality of life - todos
- [ ] think about util quality-of-life accessors
- [x] implement factory or convenience function for creating operands 

### Ideas
- [ ] merge BasicRing- and BasicRingTextsComponent ?
- [ ] implement somewhat of a store object which holds all relevant info which can be loaded by the levelmanager
